### ISSUE TITLE
You are missing 2 important files on the backend.

### ISSUE THREAD

**Issue by jakmarles** [andoniiev/ecommerce-django-react#1]
was looking at your code and notice you are missing requirements.txt and settings.py
just so you know.

**Comment by andoniiev** [comment]
Thanks, I actually forgot the requirements file, and added settings.py to gitignore in order not to share sensitive information :)

**Comment by jakmarles** [comment]
Do you mind sharing it without the sensitive information? i am trying to do the same project and it would be amazing if i can use yours as an example

**Comment by jakmarles** [comment]
> Thanks, I actually forgot the requirements file, and added settings.py to gitignore in order not to share sensitive information :)

Do you mind sharing it without the sensitive information? i am trying to do the same project and it would be amazing if i can use yours as an example, the guide i am using is very outdated and yours seems more up to date

**Comment by andoniiev** [comment]
You can check the backend/backend folder now I added settings.py file. Just insert your secret key and it should be good
